### ISSUE TITLE
Show an error message's detail

### ISSUE THREAD

**Issue by jairzh** [kevinohara80/dmc#20]
The console log always display `unknown error occurred` when compiling error.

```
[dmc] searching for local metadata
[dmc] deploying 1 metadata files
[dmc] deploy mode: dynamic
[dmc] deploy api: tooling
[dmc] loading related metadata ids
[dmc] loaded 1 ids
[dmc] creating stub files
[dmc] created 0 stub files
[dmc] creating static resources
[dmc] deployed 0 static resources
[dmc] creating container
[dmc] [create] metadata container: 1dc900000005SyRAAU
[dmc] [create] container member: ApexClass::test
[dmc] Deploying...
[dmc] * deploy status: Failed
[err] unknown error occurred
[dmc] [delete] metadata container: 1dc900000005SyRAAU
```

So can the tool display an error message's detail that will be better for debugging.

**Comment by kevinohara80** [comment]
Yeah I've been working on a solution for this. The tooling API doesn't always return compiler error messages.

For now, you can use the `--meta` flag to force the deploy to use the metadata API which has much better log results. This can also be set as a default in the config.

**Comment by kevinohara80** [comment]
@jairzh Tracked down the issue. It's in the nforce-tooling plugin. I just sent them a pull request and will update dmc as soon as it gets resolved.

**Comment by kevinohara80** [comment]
Resolved and released in the latest beta. Thanks @jairzh!

**Comment by jairzh** [comment]
You are great @kevinohara80
