### ISSUE TITLE
When will API v36.0 be supported?

### ISSUE THREAD

**Issue by tggagne** [kevinohara80/dmc#27]
So the first thing I wanted to deploy required v36 features.  

dmc config:set api_version=36
dmc deploy src/objects/objectname
[dmc] using org: orgname (default)
[err] api version v36.0 is not supported
[dmc] [NOT OK]

**Comment by kevinohara80** [comment]
The nforce dependency needed an upgrade. I just patched that. `npm update -g dmc@latest`

**Comment by tggagne** [comment]
```
DrozBook:ally-sf-cmf tgagne$ **sudo npm update -g dmc@latest**
DrozBook:ally-sf-cmf tgagne$ **dmc deploy fraudgagne src/objects/SAR__c.object** 
[dmc] using org: fraudgagne (default)
[err] **api version v36.0 is not supported**
[dmc] [NOT OK]
```
