### ISSUE TITLE
ReportType no files found

### ISSUE THREAD

**Issue by brandbarr** [kevinohara80/dmc#34]
Currently, when retrieving reportType metadata, no files are found. 

```
Bb: ~/projects/scorecard  (SC-3893) $ dmc retrieve src/reporttypes/* 
[dmc] using org: sc
[dmc] loaded .dmcignore
[dmc] matching types
[err] no files found for retrieve
[dmc] [NOT OK]
```

**Comment by kevinohara80** [comment]
@brbarr I think the correct folder is `reportType` with the capital `T`. Can you try that?

**Comment by kevinohara80** [comment]
Also, you need to wrap the reportTypes in quotes to prevent your shell from expanding the glob.
