### ISSUE TITLE
dmc retrieve does not retrieve namespaced metadata 

### ISSUE THREAD

**Issue by jdk243** [kevinohara80/dmc#39]
I'm currently working on a managed package and figured I'd use DMC to pull my project's metadata from our packaging org; none of the packaged code was retrieved. I saw #19 was a closed issue; would it be possible to provide a flag to specify namespaces that should be included in retrieve calls?

**Comment by jnottingham** [comment]
In version 1.2.3, the `retrieve` command has two options related to namespaces: `-a` will pull all namespaces and `-n` will retrieve a specified namespace. I think the default is only pulling from the null namespace.

**Comment by jdk243** [comment]
awesome, thanks!

**Comment by kevinohara80** [comment]
Thanks @jnottingham. @jdk243 let me know how that works for you.
